// resources/js/react/pages/Index.tsx
import type { Module } from '@/components/ui/saucebase';
import {
    ModuleCard,
    ModuleModal,
    useModuleList,
} from '@/components/ui/saucebase';
import { useT } from '@/i18n';
import SiteLayout from '@/layouts/SiteLayout';
import { BookOpen } from 'lucide-react';
import { useState } from 'react';

export default function Index() {
    const t = useT();
    const modules = useModuleList();
    const [selectedMod, setSelectedMod] = useState<Module | null>(null);

    return (
        <SiteLayout
            title={t('Saucebase | The best modular Laravel SaaS Starter Kit')}
            description={t(
                'Free, open-source Laravel SaaS starter kit. Ships with auth, billing, admin panel, and a modular copy-and-own architecture.',
            )}
        >
            <main className="mx-auto w-full">
                <div className="relative overflow-hidden mask-t-from-95% mask-b-from-95% px-6 md:mask-r-from-95% md:mask-l-from-95% md:px-16 lg:px-8">
                    <div className="mt-6 pt-24 pb-12">
                        <h1 className="text-foreground/80 dark:text-muted-foreground text-center text-4xl font-bold [text-shadow:0_4px_25px_color-mix(in_oklch,var(--color-primary)_15%,var(--color-background))] md:text-5xl">
                            {t('Your foundation is ready!')}
                        </h1>
                        <h2 className="text-secondary mt-1 text-center text-5xl font-bold md:text-7xl">
                            {t("Let's get started")}
                        </h2>
                        <p className="text-muted-foreground mt-3 text-center text-xl tracking-tighter md:text-3xl">
                            {t(
                                'Your recipe first. Modules for everything else',
                            )}
                        </p>
                    </div>

                    {/* Module cards */}
                    <div className="relative z-10 mx-auto grid max-w-6xl grid-cols-1 gap-8 gap-y-2 px-6 pt-8 pb-16 font-mono has-[[data-card]:hover]:*:data-card:opacity-40 sm:grid-cols-2 sm:px-10 lg:grid-cols-3 lg:px-20 xl:grid-cols-4">
                        {modules.map((mod, index) => (
                            <ModuleCard
                                key={mod.id}
                                module={mod}
                                index={index}
                                moduleClass="rotate-[-5deg] skew-x-10"
                                onSelect={setSelectedMod}
                            />
                        ))}
                    </div>

                    {/* Light mode dot pattern */}
                    <div
                        className="absolute inset-0 -top-10 -right-20 -bottom-10 -left-20 -z-1 overflow-hidden md:rotate-[-5deg] md:skew-x-10 dark:hidden"
                        style={{
                            backgroundSize: '24px',
                            backgroundPosition: 'top left',
                            backgroundImage:
                                "url('data:image/svg+xml,%3Csvg viewBox=%220 0 32 32%22 fill=%22none%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg opacity=%22.4%22 fill=%22%23011E32%22 fill-opacity=%22.24%22%3E%3Cpath fill-rule=%22evenodd%22 clip-rule=%22evenodd%22 d=%22M0 .5V6h.5V.5H6V0H0v.5ZM.5 32H0v-6h.5v5.5H6v.5H.5ZM32 0v6h-.5V.5H26V0h6Zm0 31.5V26h-.5v5.5H26v.5h6v-.5Z%22/%3E%3Cpath opacity=%22.6%22 d=%22M19 0v.5h-6V0zM19 31.5v.5h-6v-.5zM32 19h-.5v-6h.5zM.5 19H0v-6h.5z%22/%3E%3C/g%3E%3C/svg%3E')",
                        }}
                    />
                    {/* Dark mode dot pattern */}
                    <div
                        className="absolute inset-0 -top-10 -right-20 -bottom-10 -left-20 -z-1 hidden overflow-hidden md:rotate-[-5deg] md:skew-x-10 dark:block"
                        style={{
                            backgroundSize: '24px',
                            backgroundPosition: 'top left',
                            backgroundImage:
                                "url('data:image/svg+xml,%3Csvg viewBox=%220 0 32 32%22 fill=%22none%22 xmlns=%22http://www.w3.org/2000/svg%22%3E%3Cg opacity=%22.5%22 fill=%22%23ffffff%22 fill-opacity=%22.15%22%3E%3Cpath fill-rule=%22evenodd%22 clip-rule=%22evenodd%22 d=%22M0 .5V6h.5V.5H6V0H0v.5ZM.5 32H0v-6h.5v5.5H6v.5H.5ZM32 0v6h-.5V.5H26V0h6Zm0 31.5V26h-.5v5.5H26v.5h6v-.5Z%22/%3E%3Cpath opacity=%22.6%22 d=%22M19 0v.5h-6V0zM19 31.5v.5h-6v-.5zM32 19h-.5v-6h.5zM.5 19H0v-6h.5z%22/%3E%3C/g%3E%3C/svg%3E')",
                        }}
                    />

                    <div className="my-8 mb-36 flex justify-center">
                        <div className="relative inline-flex">
                            <div
                                className="stripe absolute inset-0 translate-y-3 rounded-full"
                                style={
                                    {
                                        '--mod-color': 'var(--foreground)',
                                    } as React.CSSProperties
                                }
                            />
                            <a
                                href="https://saucebase-dev.github.io/docs/"
                                className="hover:bg-foreground/80 text-background bg-foreground/90 relative flex items-center gap-2 rounded-full px-8 py-4 text-base font-semibold shadow-[0_5px_0_0_color-mix(in_oklch,var(--color-foreground)_85%,black)] transition-all duration-200 hover:-translate-y-1 hover:shadow-[0_9px_0_0_color-mix(in_oklch,var(--color-foreground)_85%,black)]"
                            >
                                <BookOpen
                                    className="size-5"
                                    aria-hidden="true"
                                />
                                {t('Read the Documentation')}
                            </a>
                        </div>
                    </div>
                </div>
            </main>

            <ModuleModal
                selectedMod={selectedMod}
                onClose={() => setSelectedMod(null)}
            />
        </SiteLayout>
    );
}

// resources/js/pages/Index.vue
<script setup lang="ts">
import Footer from '@/components/Footer.vue';
import Header from '@/components/Header.vue';
import { Head } from '@inertiajs/vue3';
import {
    CreditCard,
    Lightbulb,
    Lock,
    Map,
    Megaphone,
    Newspaper,
    Palette,
    Settings2,
} from 'lucide-vue-next';

const modules = [
    {
        id: 'auth',
        title: 'Auth',
        description:
            'Login, register, OAuth, magic links, and email verification.',
        icon: Lock,
        bg: 'bg-violet-600/20',
        text: 'text-violet-600',
        badge: 'free',
        href: 'https://saucebase-dev.github.io/docs/modules/auth',
    },
    {
        id: 'settings',
        title: 'Settings',
        description: 'User preferences and system-wide configuration.',
        icon: Settings2,
        bg: 'bg-sky-500/20',
        text: 'text-sky-500',
        badge: 'free',
        href: 'https://saucebase-dev.github.io/docs/modules/settings',
    },
    {
        id: 'billing',
        title: 'Billing',
        description:
            'Stripe subscriptions, checkout sessions, and billing portal.',
        icon: CreditCard,
        bg: 'bg-green-600/20',
        text: 'text-green-600',
        badge: 'free',
        href: 'https://saucebase-dev.github.io/docs/modules/billing',
    },
    {
        id: 'roadmap',
        title: 'Roadmap',
        description: 'Public roadmap with feature requests and voting.',
        icon: Map,
        bg: 'bg-amber-500/20',
        text: 'text-amber-500',
        badge: 'free',
        href: 'https://saucebase-dev.github.io/docs/modules/roadmap',
    },
    {
        id: 'announcements',
        title: 'Announcements',
        description: 'Site-wide banners with scheduling and dismissal.',
        icon: Megaphone,
        bg: 'bg-indigo-500/20',
        text: 'text-indigo-500',
        badge: 'free',
        href: 'https://saucebase-dev.github.io/docs/modules/announcements',
    },
    {
        id: 'themes',
        title: 'Themes',
        description:
            'Global visual editor for colors, fonts, radius, and shadows. Bake a theme into CSS without writing code.',
        icon: Palette,
        bg: 'bg-rose-500/20',
        text: 'text-rose-500',
        badge: 'free',
        href: 'https://saucebase-dev.github.io/docs/modules/themes',
    },
    {
        id: 'custom',
        title: 'Your Module',
        description:
            'Build and install your own modules with a single command.',
        icon: Lightbulb,
        bg: 'bg-gray-500/20',
        text: 'text-gray-500',
        badge: 'custom',
        href: 'https://saucebase-dev.github.io/docs/fundamentals/modules',
    },
    {
        id: 'blog',
        title: 'Blog',
        description: 'Posts, categories, tags, and admin panel.',
        icon: Newspaper,
        bg: 'bg-pink-500/20',
        text: 'text-pink-500',
        badge: 'coming-soon',
        href: null,
    },
];
</script>

<template>
    <Head>
        <title>{{ $t('Saucebase — Modular Laravel SaaS Starter Kit') }}</title>
        <meta
            name="description"
            :content="
                $t(
                    'Free, open-source Laravel SaaS starter kit. Ships with auth, billing, admin panel, and a modular copy-and-own architecture.',
                )
            "
        />
    </Head>
    <div class="relative isolate flex min-h-screen flex-col overflow-x-hidden">
        <Header />

        <main class="flex flex-1 flex-col justify-center px-6 py-24 sm:py-28">
            <div class="mx-auto max-w-7xl px-6 lg:px-8">
                <div
                    class="mx-auto grid max-w-2xl grid-cols-1 gap-x-16 gap-y-16 sm:gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-5"
                >
                    <!-- Left: content (3/5) -->
                    <div class="lg:col-span-3 lg:pt-4">
                        <h1
                            class="text-foreground text-4xl font-bold tracking-tight"
                        >
                            {{ $t("Let's get started.") }}
                        </h1>
                        <p
                            class="text-muted-foreground mt-4 text-base leading-7"
                        >
                            {{
                                $t(
                                    'Your foundation is ready. Focus on what makes your product unique the modules handle the rest.',
                                )
                            }}
                        </p>

                        <!-- Module cards -->
                        <div
                            class="group mt-8 grid grid-cols-1 gap-2 sm:grid-cols-2 lg:grid-cols-3"
                        >
                            <component
                                :is="mod.href ? 'a' : 'div'"
                                v-for="mod in modules"
                                :key="mod.id"
                                :href="mod.href ?? undefined"
                                :target="mod.href ? '_blank' : undefined"
                                :rel="
                                    mod.href ? 'noopener noreferrer' : undefined
                                "
                                class="bg-card border-border flex flex-col items-center gap-2 rounded-xl border p-4 text-center transition-all duration-200"
                                :class="
                                    mod.badge === 'coming-soon'
                                        ? 'border-dashed opacity-50 group-hover:opacity-30'
                                        : mod.badge === 'custom'
                                          ? 'cursor-pointer border-dashed group-hover:opacity-50 hover:opacity-100! hover:shadow-md'
                                          : 'cursor-pointer group-hover:opacity-50 hover:opacity-100! hover:shadow-md'
                                "
                            >
                                <div
                                    class="flex size-8 shrink-0 items-center justify-center rounded-lg"
                                    :class="[mod.bg, mod.text]"
                                >
                                    <component
                                        :is="mod.icon"
                                        class="size-4"
                                        aria-hidden="true"
                                    />
                                </div>
                                <span
                                    class="text-foreground text-sm font-medium leading-tight"
                                >
                                    {{ $t(mod.title) }}
                                </span>
                                <p
                                    class="text-muted-foreground line-clamp-2 text-xs leading-snug"
                                >
                                    {{ $t(mod.description) }}
                                </p>
                            </component>
                        </div>

                        <!-- CTA -->
                        <div class="mt-8">
                            <a
                                href="https://saucebase-dev.github.io/docs/"
                                target="_blank"
                                rel="noopener noreferrer"
                                class="bg-foreground text-background hover:bg-foreground/90 flex w-full items-center justify-center rounded-xl px-6 py-3 text-sm font-semibold transition-all md:w-auto md:inline-flex"
                            >
                                {{ $t('Read the Documentation') }}
                            </a>
                        </div>
                    </div>

                    <!-- Right: screenshot (2/5), overflows to edge -->
                    <img
                        src="/images/screenshots/dashboard-dark.png"
                        :alt="$t('Saucebase dashboard screenshot')"
                        class="w-3xl max-w-none rounded-xl shadow-xl ring-1 ring-white/10 not-dark:hidden sm:w-228 lg:col-span-2"
                    />
                    <img
                        src="/images/screenshots/dashboard-light.png"
                        :alt="$t('Saucebase dashboard screenshot')"
                        class="w-3xl max-w-none rounded-xl shadow-2xl ring-1 ring-gray-400/20 sm:w-228 lg:col-span-2 dark:hidden"
                    />
                </div>
            </div>
        </main>

        <Footer />
    </div>
</template>
