// resources/js/react/components/Header.tsx
import { useModules } from '@/hooks/useModules';
import { useT } from '@/i18n';
import { cn } from '@/lib/utils';
import type { MenuItem } from '@/types/navigation';
import { Link, usePage } from '@inertiajs/react';
import { ArrowRight, ExternalLink, Menu, X } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import AppLogo from './AppLogo';
import LanguageSelector from './LanguageSelector';
import ThemeSelector from './ThemeSelector';

export default function Header() {
    const t = useT();
    const page = usePage();
    const { has } = useModules();
    const [isScrolled, setIsScrolled] = useState(false);
    const [isVisible, setIsVisible] = useState(true);
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const headerRef = useRef<HTMLElement>(null);
    const lastScrollY = useRef(0);

    const landingNav = ((page.props.navigation as Record<string, unknown>)
        ?.landing ?? []) as MenuItem[];
    const auth = page.props.auth as { user?: unknown } | undefined;
    const isLoggedIn = auth?.user != null;
    const isGuest = has('auth') && !isLoggedIn;

    useEffect(() => {
        const handleScroll = () => {
            // Locking body scroll (e.g. ModuleModal) collapses the scrollable
            // height, clamping window.scrollY to 0 and firing a spurious scroll
            // event — ignore it so the header doesn't slide back into view.
            if (document.body.style.overflow === 'hidden') return;

            const currentScrollY = window.scrollY;
            const headerHeight = headerRef.current?.offsetHeight ?? 80;

            setIsScrolled(currentScrollY > 10);

            if (currentScrollY < headerHeight) {
                setIsVisible(true);
            } else if (currentScrollY < lastScrollY.current) {
                setIsVisible(true);
            } else if (currentScrollY > lastScrollY.current) {
                setIsVisible(false);
                setMobileMenuOpen(false);
            }

            lastScrollY.current = currentScrollY;
        };

        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    return (
        <header
            ref={headerRef}
            className={`fixed top-0 right-0 left-0 z-50 transition-all duration-300 ${isScrolled ? 'dark:border-b-border/25 border-b bg-white/5 shadow-2xl backdrop-blur-lg' : 'bg-transparent'} ${isVisible ? 'translate-y-0' : '-translate-y-full'}`}
        >
            <nav className="mx-auto max-w-7xl px-6 py-3">
                <div className="flex items-center justify-between">
                    {/* Logo */}
                    <Link
                        href="/"
                        className="flex shrink-0 items-center transition-opacity hover:opacity-80"
                    >
                        <AppLogo size="md" showText />
                    </Link>

                    {/* Centered navigation */}
                    <div className="absolute left-1/2 hidden -translate-x-1/2 items-center space-x-1 lg:flex">
                        {landingNav.map((item) => (
                            <a
                                key={item.slug}
                                href={item.url}
                                target={item.newPage ? '_blank' : '_self'}
                                className={cn(
                                    'after:bg-primary text-muted-foreground hover:text-foreground relative px-4 py-2 text-sm font-semibold transition-all duration-300 after:absolute after:bottom-0 after:left-1/2 after:h-0.5 after:w-0 after:-translate-x-1/2 after:rounded-xl after:transition-all after:duration-300 hover:after:w-3/4',
                                    item.class,
                                )}
                            >
                                {t(item.title)}
                                {item.newPage && (
                                    <ExternalLink className="-mt-1 ml-1 inline-block size-3.5" />
                                )}
                            </a>
                        ))}
                    </div>

                    {/* Right side */}
                    <div className="hidden items-center space-x-3 lg:flex">
                        <div className="flex items-center space-x-1">
                            <LanguageSelector mode="standalone" />
                            <ThemeSelector mode="standalone" />
                        </div>
                        {isGuest && (
                            <>
                                <Link
                                    href={route('login')}
                                    className="text-muted-foreground hover:bg-accent hover:text-accent-foreground rounded-xl px-4 py-2 text-sm font-medium transition-all duration-200"
                                >
                                    {t('Sign In')}
                                </Link>
                                <Link
                                    href={route('register')}
                                    className="bg-primary text-primary-foreground hover:bg-primary/90 focus:ring-primary inline-flex items-center justify-center rounded-xl px-5 py-2.5 text-sm font-semibold transition-all duration-200 focus:ring-2 focus:ring-offset-2 focus:outline-none"
                                >
                                    {t('Get Started')}
                                </Link>
                            </>
                        )}
                        {route().has('dashboard') && isLoggedIn && (
                            <Link
                                href={route('dashboard')}
                                className="bg-primary text-primary-foreground hover:bg-primary/90 focus:ring-primary inline-flex items-center justify-center rounded-xl px-5 py-2.5 text-sm font-semibold transition-all duration-200"
                            >
                                {t('Dashboard')}
                            </Link>
                        )}
                        {route().has('logout') && isLoggedIn && (
                            <Link
                                href={route('logout')}
                                className="text-muted-foreground hover:bg-accent hover:text-accent-foreground rounded-xl px-4 py-2 text-sm font-medium transition-all duration-200"
                            >
                                {t('Logout')}
                            </Link>
                        )}
                    </div>

                    {/* Mobile menu button */}
                    <div className="flex items-center space-x-3 lg:hidden">
                        <LanguageSelector mode="standalone" />
                        <ThemeSelector mode="standalone" />
                        <button
                            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
                            aria-label={
                                mobileMenuOpen
                                    ? t('Close mobile menu')
                                    : t('Open mobile menu')
                            }
                            aria-expanded={mobileMenuOpen}
                            className="text-muted-foreground hover:bg-accent hover:text-accent-foreground rounded-xl p-2 transition-colors duration-200"
                        >
                            {mobileMenuOpen ? (
                                <X className="h-6 w-6" />
                            ) : (
                                <Menu className="h-6 w-6" />
                            )}
                        </button>
                    </div>
                </div>

                {/* Mobile menu */}
                {mobileMenuOpen && (
                    <div className="border-border/40 bg-background/80 mx-2 mt-4 rounded-lg border-t pb-6 backdrop-blur-sm lg:hidden">
                        <div className="flex flex-col space-y-1 px-2 pt-4">
                            {landingNav.map((item) => (
                                <a
                                    key={item.slug}
                                    href={item.url}
                                    target={item.newPage ? '_blank' : '_self'}
                                    className={cn(
                                        'after:bg-primary hover:text-primary text-foreground relative px-4 py-3 text-base font-semibold transition-all duration-300 after:absolute after:bottom-1 after:left-4 after:h-0.5 after:w-0 after:rounded-xl after:transition-all after:duration-300 hover:after:w-1/2',
                                        item.class,
                                    )}
                                    onClick={() => setMobileMenuOpen(false)}
                                >
                                    {t(item.title)}
                                </a>
                            ))}

                            <div className="border-border/60 mt-2 border-t pt-4">
                                {isGuest && (
                                    <div className="flex gap-3">
                                        <Link
                                            href={route('login')}
                                            className="border-border text-foreground hover:bg-accent flex-1 rounded-xl border px-4 py-2.5 text-center text-sm font-medium transition-all duration-200"
                                            onClick={() =>
                                                setMobileMenuOpen(false)
                                            }
                                        >
                                            {t('Sign In')}
                                        </Link>
                                        <Link
                                            href={route('register')}
                                            className="bg-primary text-primary-foreground hover:bg-primary/90 flex flex-1 items-center justify-center gap-1.5 rounded-xl px-4 py-2.5 text-sm font-semibold transition-all duration-200"
                                            onClick={() =>
                                                setMobileMenuOpen(false)
                                            }
                                        >
                                            {t('Get Started')}
                                            <ArrowRight className="h-3.5 w-3.5" />
                                        </Link>
                                    </div>
                                )}
                                {isLoggedIn && (
                                    <Link
                                        href={route('dashboard')}
                                        className="bg-primary text-primary-foreground hover:bg-primary/90 flex w-full items-center justify-center gap-1.5 rounded-xl px-4 py-2.5 text-sm font-semibold transition-all duration-200"
                                        onClick={() => setMobileMenuOpen(false)}
                                    >
                                        {t('Dashboard')}
                                        <ArrowRight className="h-3.5 w-3.5" />
                                    </Link>
                                )}
                            </div>
                        </div>
                    </div>
                )}
            </nav>
        </header>
    );
}

// resources/js/components/Header.vue
<script setup lang="ts">
import { modules } from '@/composables/useModules';
import type { MenuItem } from '@/types/navigation';
import { Link, usePage } from '@inertiajs/vue3';
import { ArrowRight, ExternalLink } from 'lucide-vue-next';
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import IconMenu from '~icons/heroicons/bars-3';
import IconX from '~icons/heroicons/x-mark';
import AppLogo from './AppLogo.vue';
import LanguageSelector from './LanguageSelector.vue';
import ThemeSelector from './ThemeSelector.vue';

const page = usePage();
const landingNav = computed<MenuItem[]>(
    () => (page.props.navigation as { landing?: MenuItem[] })?.landing || [],
);

const isScrolled = ref(false);
const isVisible = ref(true);
const mobileMenuOpen = ref(false);
const headerRef = ref<HTMLElement | null>(null);
let lastScrollY = 0;

const handleScroll = () => {
    const currentScrollY = window.scrollY;
    const headerHeight = headerRef.value?.offsetHeight ?? 80;

    isScrolled.value = currentScrollY > 10;

    if (currentScrollY < headerHeight) {
        isVisible.value = true;
    } else if (currentScrollY < lastScrollY) {
        isVisible.value = true;
    } else if (currentScrollY > lastScrollY) {
        isVisible.value = false;
        mobileMenuOpen.value = false;
    }

    lastScrollY = currentScrollY;
};

onMounted(() => {
    window.addEventListener('scroll', handleScroll);
});

onBeforeUnmount(() => {
    window.removeEventListener('scroll', handleScroll);
});
</script>

<template>
    <header
        ref="headerRef"
        class="fixed top-0 right-0 left-0 z-50 transition-all duration-300"
        :class="[
            isScrolled
                ? 'dark:border-b-border/25 border-b bg-white/5 shadow-2xl backdrop-blur-lg'
                : 'bg-transparent',
            isVisible ? 'translate-y-0' : '-translate-y-full',
        ]"
    >
        <nav class="mx-auto max-w-7xl px-6 py-3">
            <div class="flex items-center justify-between">
                <!-- Logo (Left) -->
                <Link
                    href="/"
                    class="flex shrink-0 items-center transition-opacity hover:opacity-80"
                >
                    <AppLogo size="md" :showText="true" />
                </Link>

                <!-- Landing navigation - Centered -->
                <div
                    class="absolute left-1/2 hidden -translate-x-1/2 items-center space-x-1 lg:flex"
                >
                    <a
                        v-for="item in landingNav"
                        :key="item.slug"
                        :href="item.url"
                        :target="item.newPage ? '_blank' : '_self'"
                        class="after:bg-primary text-muted-foreground hover:text-foreground relative px-4 py-2 text-sm font-semibold transition-all duration-300 after:absolute after:bottom-0 after:left-1/2 after:h-0.5 after:w-0 after:-translate-x-1/2 after:rounded-xl after:transition-all after:duration-300 hover:after:w-3/4"
                    >
                        {{ $t(item.title) }}
                        <ExternalLink
                            v-if="item.newPage"
                            class="-mt-1 ml-1 inline-block size-3.5"
                        />
                    </a>
                </div>

                <!-- Right side actions -->
                <div class="hidden items-center space-x-3 lg:flex">
                    <div class="flex items-center space-x-1">
                        <LanguageSelector mode="standalone" />
                        <ThemeSelector mode="standalone" />
                    </div>

                    <Link
                        v-if="modules().has('Auth') && !$page.props.auth?.user"
                        :href="route('login')"
                        class="text-muted-foreground hover:bg-accent hover:text-accent-foreground rounded-xl px-4 py-2 text-sm font-medium transition-all duration-200"
                    >
                        {{ $t('Sign In') }}
                    </Link>

                    <Link
                        v-if="modules().has('Auth') && !$page.props.auth?.user"
                        :href="route('register')"
                        class="bg-primary text-primary-foreground hover:bg-primary/90 focus:ring-primary inline-flex items-center justify-center rounded-xl px-5 py-2.5 text-sm font-semibold transition-all duration-200 hover:scale-105 focus:ring-2 focus:ring-offset-2 focus:outline-none"
                    >
                        {{ $t('Get Started') }}
                    </Link>

                    <Link
                        v-if="
                            route().has('dashboard') && $page.props.auth?.user
                        "
                        :href="route('dashboard')"
                        class="bg-primary text-primary-foreground hover:bg-primary/90 focus:ring-primary inline-flex items-center justify-center rounded-xl px-5 py-2.5 text-sm font-semibold transition-all duration-200 hover:scale-105 focus:ring-2 focus:ring-offset-2 focus:outline-none"
                    >
                        {{ $t('Dashboard') }}
                    </Link>
                    <Link
                        v-if="route().has('logout') && $page.props.auth?.user"
                        :href="route('logout')"
                        class="text-muted-foreground hover:bg-accent hover:text-accent-foreground rounded-xl px-4 py-2 text-sm font-medium transition-all duration-200"
                    >
                        {{ $t('Logout') }}
                    </Link>
                </div>

                <!-- Mobile Menu Button - Better positioning -->
                <div class="flex items-center space-x-3 lg:hidden">
                    <LanguageSelector mode="standalone" />
                    <ThemeSelector mode="standalone" />
                    <button
                        @click="mobileMenuOpen = !mobileMenuOpen"
                        :aria-label="
                            mobileMenuOpen
                                ? $t('Close mobile menu')
                                : $t('Open mobile menu')
                        "
                        :aria-expanded="mobileMenuOpen"
                        class="text-muted-foreground hover:bg-accent hover:text-accent-foreground rounded-xl p-2 transition-colors duration-200"
                    >
                        <IconMenu v-if="!mobileMenuOpen" class="h-6 w-6" />
                        <IconX v-else class="h-6 w-6" />
                    </button>
                </div>
            </div>

            <!-- Mobile Menu - Enhanced with animations -->
            <Transition
                enter-active-class="transition-all duration-300 ease-out"
                enter-from-class="opacity-0 transform -translate-y-2"
                enter-to-class="opacity-100 transform translate-y-0"
                leave-active-class="transition-all duration-200 ease-in"
                leave-from-class="opacity-100 transform translate-y-0"
                leave-to-class="opacity-0 transform -translate-y-2"
            >
                <div
                    v-if="mobileMenuOpen"
                    class="border-border/40 bg-background/80 mx-2 mt-4 rounded-lg border-t pb-6 backdrop-blur-sm lg:hidden"
                >
                    <div class="flex flex-col space-y-1 px-2 pt-4">
                        <!-- Landing navigation (anchor links) -->
                        <a
                            v-for="item in landingNav"
                            :key="item.slug"
                            :href="item.url"
                            :target="item.newPage ? '_blank' : '_self'"
                            class="after:bg-primary hover:text-primary text-foreground relative px-4 py-3 text-base font-semibold transition-all duration-300 after:absolute after:bottom-1 after:left-4 after:h-0.5 after:w-0 after:rounded-xl after:transition-all after:duration-300 hover:after:w-1/2"
                            @click="mobileMenuOpen = false"
                        >
                            {{ $t(item.title) }}
                        </a>

                        <!-- Mobile auth actions -->
                        <div class="border-border/60 mt-2 border-t pt-4">
                            <!-- Unauthenticated: side-by-side buttons -->
                            <div
                                v-if="
                                    modules().has('auth') &&
                                    !$page.props.auth?.user
                                "
                                class="flex gap-3"
                            >
                                <Link
                                    :href="route('login')"
                                    class="border-border text-foreground hover:bg-accent flex-1 rounded-xl border px-4 py-2.5 text-center text-sm font-medium transition-all duration-200"
                                    @click="mobileMenuOpen = false"
                                >
                                    {{ $t('Sign In') }}
                                </Link>
                                <Link
                                    :href="route('register')"
                                    class="bg-primary text-primary-foreground hover:bg-primary/90 flex flex-1 items-center justify-center gap-1.5 rounded-xl px-4 py-2.5 text-sm font-semibold transition-all duration-200"
                                    @click="mobileMenuOpen = false"
                                >
                                    {{ $t('Get Started') }}
                                    <ArrowRight class="h-3.5 w-3.5" />
                                </Link>
                            </div>

                            <!-- Authenticated: single dashboard button -->
                            <Link
                                v-if="
                                    modules().has('auth') &&
                                    $page.props.auth?.user
                                "
                                :href="route('dashboard')"
                                class="bg-primary text-primary-foreground hover:bg-primary/90 flex w-full items-center justify-center gap-1.5 rounded-xl px-4 py-2.5 text-sm font-semibold transition-all duration-200"
                                @click="mobileMenuOpen = false"
                            >
                                {{ $t('Dashboard') }}
                                <ArrowRight class="h-3.5 w-3.5" />
                            </Link>
                        </div>
                    </div>
                </div>
            </Transition>
        </nav>
    </header>
</template>
