// resources/js/react/components/Footer.tsx
import { useSettings } from '@/hooks/useSettings';
import { useT } from '@/i18n';
import { Link } from '@inertiajs/react';
import { Heart } from 'lucide-react';

export default function Footer() {
    const t = useT();
    const settings = useSettings();

    return (
        <footer className="relative mt-auto w-full overflow-hidden pb-12 sm:pb-48">
            <div className="relative z-10 mx-4 py-8 min-[450px]:mx-auto min-[450px]:max-w-7xl min-[450px]:px-6">
                <div className="text-muted-foreground flex w-full flex-col items-center justify-between gap-4 text-sm md:flex-row">
                    <div className="flex flex-col items-center gap-y-1 md:flex-row md:items-center md:gap-x-6 md:gap-y-0">
                        <span data-testid="footer-app-name">
                            © {new Date().getFullYear()}{' '}
                            {settings.general.site_name}
                        </span>
                        <a
                            href="https://github.com/saucebase-dev/saucebase"
                            className="hover:text-foreground"
                        >
                            {t('GitHub')}
                        </a>
                        <a
                            href="https://saucebase-dev.github.io/docs/"
                            className="hover:text-foreground"
                        >
                            {t('Documentation')}
                        </a>
                        {route().has('privacy') && (
                            <Link
                                href={route('privacy')}
                                className="hover:text-foreground"
                            >
                                {t('Privacy')}
                            </Link>
                        )}
                        {route().has('terms') && (
                            <Link
                                href={route('terms')}
                                className="hover:text-foreground"
                            >
                                {t('Terms')}
                            </Link>
                        )}
                    </div>
                    <div className="flex items-center gap-1">
                        <span>{t('Crafted with')}</span>
                        <Heart className="h-4 w-4 text-red-500" />
                        <span>{t('for developers')}</span>
                        <span>{t('by :name', { name: 'Renan Roble' })}</span>
                    </div>
                </div>
            </div>
            <div className="absolute bottom-0 z-0 translate-y-[20%] scale-105 px-4 font-mono">
                <p
                    className="text-center text-[21vw] leading-none font-black -tracking-widest select-none"
                    data-testid="footer-watermark"
                >
                    {settings.general.site_name === 'Saucebase' ? (
                        <>
                            <span className="text-foreground/5">Sauce</span>
                            <span className="text-foreground/10">base</span>
                        </>
                    ) : (
                        <span className="text-foreground/10">
                            {settings.general.site_name}
                        </span>
                    )}
                </p>
            </div>
        </footer>
    );
}

// resources/js/vue/components/Footer.vue
<script setup lang="ts">
import { useSettings } from '@/composables/useSettings';
import { Link } from '@inertiajs/vue3';
import IconHeart from '~icons/heroicons/heart';

const settings = useSettings();
</script>

<template>
    <footer class="relative mt-auto w-full overflow-hidden pb-12 sm:pb-48">
        <div
            class="relative z-10 mx-4 py-8 min-[450px]:mx-auto min-[450px]:max-w-7xl min-[450px]:px-6"
        >
            <div
                class="text-muted-foreground flex w-full flex-col items-center justify-between gap-4 text-sm md:flex-row"
            >
                <div
                    class="flex flex-col items-center gap-y-1 md:flex-row md:items-center md:gap-x-6 md:gap-y-0"
                >
                    <span data-testid="footer-app-name">
                        © {{ new Date().getFullYear() }}
                        {{ settings.general.site_name }}
                    </span>
                    <a
                        href="https://github.com/saucebase-dev/saucebase"
                        class="hover:text-foreground"
                    >
                        {{ $t('GitHub') }}
                    </a>
                    <a
                        href="https://saucebase-dev.github.io/docs/"
                        class="hover:text-foreground"
                    >
                        {{ $t('Documentation') }}
                    </a>
                    <Link
                        :href="route('privacy')"
                        class="hover:text-foreground"
                    >
                        {{ $t('Privacy') }}
                    </Link>
                    <Link :href="route('terms')" class="hover:text-foreground">
                        {{ $t('Terms') }}
                    </Link>
                </div>
                <div class="flex items-center gap-1">
                    <span>{{ $t('Crafted with') }}</span>
                    <IconHeart class="h-4 w-4 text-red-500" />
                    <span>{{ $t('for developers') }}</span>
                    <span>{{ $t('by :name', { name: 'Renan Roble' }) }}</span>
                </div>
            </div>
        </div>
        <div
            class="absolute inset-x-0 bottom-0 z-0 w-full translate-y-[20%] scale-105 px-4 font-mono"
        >
            <p
                class="text-center text-[min(21vw,400px)] leading-none font-black -tracking-widest select-none"
                data-testid="footer-watermark"
            >
                <template v-if="settings.general.site_name === 'Saucebase'">
                    <span class="text-foreground/5">Sauce</span
                    ><span class="text-foreground/10">base</span>
                </template>
                <span v-else class="text-foreground/10">
                    {{ settings.general.site_name }}
                </span>
            </p>
        </div>
    </footer>
</template>
